"""Build the static, server-free version of the web app (for GitHub Pages or any static host).

    python -m facial build-site --out site

Everything runs in the browser: MediaPipe, the five-field measurements, the voice
analysis and the judge (rules by default, an AI model when the viewer adds an API key).
The judge prompt and provider list are generated from judge.py and providers.py so
both versions ask the models the same thing.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

from .expressions import EMOTIONS, EXPRESSION_EMOTION, EXPRESSIONS, TRAITS
from .jev import JEV_ESCALATE, JEV_INTENTS, JEV_QUESTIONS, JEV_ROUTES, JEV_SCALES
from .judge import (DEFAULT_MODEL, FALLBACK_MODELS, JSON_RULE, LANGUAGE_RULES, SCHEMA, SYSTEM_PROMPT, WRITE_SCHEMA,
                    WRITER_RULE)
from .providers import OPENAI_REASONING, PROVIDERS, THINKING_MODELS
from .models import DEFAULT_MODEL_DIR, ensure_models, ensure_web_vendor

WEB_DIR = Path(__file__).resolve().parent / "web"
PROMPT_JS = WEB_DIR / "prompt.js"


def prompt_js() -> str:
    """JavaScript module mirroring the judge prompt, schemas, providers and Jev questions."""
    parts = [
        "// Generated by facial/webbuild.py from facial/judge.py, providers.py and jev.py; do not edit by hand.",
        f"export const SYSTEM_PROMPT = {json.dumps(SYSTEM_PROMPT, ensure_ascii=False)};",
        f"export const LANGUAGE_RULES = {json.dumps(LANGUAGE_RULES, ensure_ascii=False)};",
        f"export const SCHEMA = {json.dumps(SCHEMA)};",
        f"export const DEFAULT_MODEL = {json.dumps(DEFAULT_MODEL)};",
        f"export const FALLBACK_MODELS = {json.dumps(sorted(FALLBACK_MODELS))};",
        f"export const JSON_RULE = {json.dumps(JSON_RULE)};",
        f"export const PROVIDERS = {json.dumps(PROVIDERS, ensure_ascii=False)};",
        f"export const THINKING_MODELS = {json.dumps(THINKING_MODELS)};",
        f"export const OPENAI_REASONING = {json.dumps(OPENAI_REASONING)};",
        f"export const WRITE_SCHEMA = {json.dumps(WRITE_SCHEMA)};",
        f"export const WRITER_RULE = {json.dumps(WRITER_RULE)};",
        f"export const JEV_ROUTES = {json.dumps(JEV_ROUTES)};",
        f"export const JEV_SCALES = {json.dumps(JEV_SCALES)};",
        f"export const JEV_INTENTS = {json.dumps(JEV_INTENTS, ensure_ascii=False)};",
        f"export const JEV_QUESTIONS = {json.dumps(JEV_QUESTIONS)};",
        f"export const JEV_ESCALATE = {json.dumps(JEV_ESCALATE)};",
        f"export const EXPRESSIONS = {json.dumps(EXPRESSIONS, ensure_ascii=False)};",
        f"export const EMOTIONS = {json.dumps(EMOTIONS, ensure_ascii=False)};",
        f"export const EXPRESSION_EMOTION = {json.dumps(EXPRESSION_EMOTION)};",
        f"export const TRAITS = {json.dumps(TRAITS, ensure_ascii=False)};",
    ]
    return "\n".join(parts) + "\n"


def write_prompt_js() -> Path:
    PROMPT_JS.write_text(prompt_js(), encoding="utf-8")
    return PROMPT_JS


def build_site(out: Path) -> Path:
    """Copy the web app, models and MediaPipe runtime into `out` as a static site."""
    out = Path(out)
    if out.exists():
        shutil.rmtree(out)
    write_prompt_js()
    ensure_models()
    vendor = ensure_web_vendor()

    shutil.copytree(WEB_DIR, out / "static", ignore=shutil.ignore_patterns("index.html", "__pycache__"))
    shutil.copy(WEB_DIR / "index.html", out / "index.html")
    (out / "static" / "config.js").write_text('export const CONFIG = { mode: "static" };\n', encoding="utf-8")
    # The service worker must sit at the site root to control the whole app.
    shutil.move(out / "static" / "sw.js", out / "sw.js")
    shutil.move(out / "static" / "manifest.webmanifest", out / "manifest.webmanifest")

    models = out / "models"
    models.mkdir()
    for task in DEFAULT_MODEL_DIR.glob("*.task"):
        shutil.copy(task, models / task.name)
    web = models / "web" / "tasks-vision"
    (web / "wasm").mkdir(parents=True)
    shutil.copy(vendor / "vision_bundle.mjs", web / "vision_bundle.mjs")
    for f in (vendor / "wasm").iterdir():
        if "module" not in f.name:  # the page only loads the classic SIMD / no-SIMD builds
            shutil.copy(f, web / "wasm" / f.name)
    (out / ".nojekyll").write_text("")  # serve files as-is on GitHub Pages
    return out
